#!/bin/sh

# Check if the Maven build is successful

mvn clean package -DskipTests

# If the Maven build is not successful, exit with an error code
if [ $? -ne 0 ]; then
  echo "Maven build failed"
  exit 1
fi
