server:
  port: 28080
  servlet:
      context-path: /service
springdoc:
  swagger-ui:
    path: /api

jira:
  userName:
  token:
  project:
  issueType:
  issueStatus:
  domain:
  baseuri:

############ Swagger Config ###############
apiTitle: "Jira Integration Service"
apiDescription: "Connects to JIRA through API and retrieves tickets based on JQL"
apiVersion: "1.0.0"
apiContactName: "Bhaskar Mantrala"
apiContactEmail: ""
apiContactUrl: "https://github.com/BhaskarMantralaHub"